# Use the official Ollama image as a parent image
FROM ollama/ollama

# Expose the port Ollama API will run on
EXPOSE 11434

# Copy the entry point script
COPY ollamaEntryPoint.sh /app/ollamaEntryPoint.sh

# Make the entry point script executable
RUN chmod +x /app/ollamaEntryPoint.sh

# Set the entry point
ENTRYPOINT ["/app/ollamaEntryPoint.sh"]